### ISSUE TITLE
CSS not working correctly

### ISSUE THREAD

**Issue by surahmans** [rainlab/blog-plugin#144]
Hi, I have a little question how to fix this case?
![screen shot 2015-10-19 at 12 46 03 pm](https://cloud.githubusercontent.com/assets/8978940/10570603/ee567182-765f-11e5-87a6-a1d682e22aa3.png)

my fields.yaml like below,

```
secondaryTabs:
    stretch: true
    fields:
        content:
            tab: rainlab.blog::lang.post.tab_edit
            type: RainLab\Blog\FormWidgets\BlogMarkdown
            cssClass: field-slim blog-post-preview
            stretch: true
            mode: split
        content_id:
            tab: rainlab.blog::lang.post.tab_edit
            type: RainLab\Blog\FormWidgets\BlogMarkdown
            cssClass: field-slim blog-post-preview
            stretch: true
            mode: split
```

I copied the content field and only change to 'content_id'. But, why I got the result like above?

thanks,
